---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8000}]
  - ["forwarded_port", {guest: 8080, host: 8080}]

  driver_config:
    require_chef_omnibus: 11.12.8

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[icanhazdevops]
      - recipe[logrotate]
